// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: guest/v1/guest.proto

package guestproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunJobResponse_Outcome int32

const (
	RunJobResponse_OUTCOME_UNSPECIFIED RunJobResponse_Outcome = 0
	RunJobResponse_ACCEPTED            RunJobResponse_Outcome = 1
	RunJobResponse_ALREADY_RUNNING     RunJobResponse_Outcome = 2
	RunJobResponse_ALREADY_COMPLETED   RunJobResponse_Outcome = 3
	RunJobResponse_CONFLICT            RunJobResponse_Outcome = 4
)

// Enum value maps for RunJobResponse_Outcome.
var (
	RunJobResponse_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "ACCEPTED",
		2: "ALREADY_RUNNING",
		3: "ALREADY_COMPLETED",
		4: "CONFLICT",
	}
	RunJobResponse_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"ACCEPTED":            1,
		"ALREADY_RUNNING":     2,
		"ALREADY_COMPLETED":   3,
		"CONFLICT":            4,
	}
)

func (x RunJobResponse_Outcome) Enum() *RunJobResponse_Outcome {
	p := new(RunJobResponse_Outcome)
	*p = x
	return p
}

func (x RunJobResponse_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunJobResponse_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_guest_v1_guest_proto_enumTypes[0].Descriptor()
}

func (RunJobResponse_Outcome) Type() protoreflect.EnumType {
	return &file_guest_v1_guest_proto_enumTypes[0]
}

func (x RunJobResponse_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunJobResponse_Outcome.Descriptor instead.
func (RunJobResponse_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{5, 0}
}

type LogChunk_Stream int32

const (
	LogChunk_STREAM_UNSPECIFIED LogChunk_Stream = 0
	LogChunk_STDOUT             LogChunk_Stream = 1
	LogChunk_STDERR             LogChunk_Stream = 2
)

// Enum value maps for LogChunk_Stream.
var (
	LogChunk_Stream_name = map[int32]string{
		0: "STREAM_UNSPECIFIED",
		1: "STDOUT",
		2: "STDERR",
	}
	LogChunk_Stream_value = map[string]int32{
		"STREAM_UNSPECIFIED": 0,
		"STDOUT":             1,
		"STDERR":             2,
	}
)

func (x LogChunk_Stream) Enum() *LogChunk_Stream {
	p := new(LogChunk_Stream)
	*p = x
	return p
}

func (x LogChunk_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogChunk_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_guest_v1_guest_proto_enumTypes[1].Descriptor()
}

func (LogChunk_Stream) Type() protoreflect.EnumType {
	return &file_guest_v1_guest_proto_enumTypes[1]
}

func (x LogChunk_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogChunk_Stream.Descriptor instead.
func (LogChunk_Stream) EnumDescriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{9, 0}
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_guest_v1_guest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{0}
}

type HelloResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BootId            string                 `protobuf:"bytes,1,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	AgentBuild        string                 `protobuf:"bytes,2,opt,name=agent_build,json=agentBuild,proto3" json:"agent_build,omitempty"`
	ProtocolMajor     uint32                 `protobuf:"varint,3,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	Capabilities      []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Slots             []*SlotInfo            `protobuf:"bytes,5,rep,name=slots,proto3" json:"slots,omitempty"`
	GoldenFingerprint string                 `protobuf:"bytes,6,opt,name=golden_fingerprint,json=goldenFingerprint,proto3" json:"golden_fingerprint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_guest_v1_guest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *HelloResponse) GetAgentBuild() string {
	if x != nil {
		return x.AgentBuild
	}
	return ""
}

func (x *HelloResponse) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *HelloResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HelloResponse) GetSlots() []*SlotInfo {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *HelloResponse) GetGoldenFingerprint() string {
	if x != nil {
		return x.GoldenFingerprint
	}
	return ""
}

type SlotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Busy          bool                   `protobuf:"varint,2,opt,name=busy,proto3" json:"busy,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotInfo) Reset() {
	*x = SlotInfo{}
	mi := &file_guest_v1_guest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotInfo) ProtoMessage() {}

func (x *SlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotInfo.ProtoReflect.Descriptor instead.
func (*SlotInfo) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{2}
}

func (x *SlotInfo) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SlotInfo) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

func (x *SlotInfo) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type RunJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Slot          uint32                 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	JitConfig     string                 `protobuf:"bytes,3,opt,name=jit_config,json=jitConfig,proto3" json:"jit_config,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Meta          *JobMeta               `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunJobRequest) Reset() {
	*x = RunJobRequest{}
	mi := &file_guest_v1_guest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunJobRequest) ProtoMessage() {}

func (x *RunJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunJobRequest.ProtoReflect.Descriptor instead.
func (*RunJobRequest) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{3}
}

func (x *RunJobRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *RunJobRequest) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *RunJobRequest) GetJitConfig() string {
	if x != nil {
		return x.JitConfig
	}
	return ""
}

func (x *RunJobRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunJobRequest) GetMeta() *JobMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type JobMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	JobId         int64                  `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	RunId         int64                  `protobuf:"varint,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	RunnerName    string                 `protobuf:"bytes,4,opt,name=runner_name,json=runnerName,proto3" json:"runner_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobMeta) Reset() {
	*x = JobMeta{}
	mi := &file_guest_v1_guest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobMeta) ProtoMessage() {}

func (x *JobMeta) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobMeta.ProtoReflect.Descriptor instead.
func (*JobMeta) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{4}
}

func (x *JobMeta) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *JobMeta) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *JobMeta) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *JobMeta) GetRunnerName() string {
	if x != nil {
		return x.RunnerName
	}
	return ""
}

type RunJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       RunJobResponse_Outcome `protobuf:"varint,1,opt,name=outcome,proto3,enum=gha.guest.v1.RunJobResponse_Outcome" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunJobResponse) Reset() {
	*x = RunJobResponse{}
	mi := &file_guest_v1_guest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunJobResponse) ProtoMessage() {}

func (x *RunJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunJobResponse.ProtoReflect.Descriptor instead.
func (*RunJobResponse) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{5}
}

func (x *RunJobResponse) GetOutcome() RunJobResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return RunJobResponse_OUTCOME_UNSPECIFIED
}

type JobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	FromSequence  uint64                 `protobuf:"varint,2,opt,name=from_sequence,json=fromSequence,proto3" json:"from_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusRequest) Reset() {
	*x = JobStatusRequest{}
	mi := &file_guest_v1_guest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusRequest) ProtoMessage() {}

func (x *JobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusRequest.ProtoReflect.Descriptor instead.
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{6}
}

func (x *JobStatusRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *JobStatusRequest) GetFromSequence() uint64 {
	if x != nil {
		return x.FromSequence
	}
	return 0
}

type JobStatusEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sequence uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*JobStatusEvent_Phase
	//	*JobStatusEvent_Log
	//	*JobStatusEvent_Heartbeat
	//	*JobStatusEvent_Result
	Event         isJobStatusEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusEvent) Reset() {
	*x = JobStatusEvent{}
	mi := &file_guest_v1_guest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusEvent) ProtoMessage() {}

func (x *JobStatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusEvent.ProtoReflect.Descriptor instead.
func (*JobStatusEvent) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{7}
}

func (x *JobStatusEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *JobStatusEvent) GetEvent() isJobStatusEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *JobStatusEvent) GetPhase() *PhaseChange {
	if x != nil {
		if x, ok := x.Event.(*JobStatusEvent_Phase); ok {
			return x.Phase
		}
	}
	return nil
}

func (x *JobStatusEvent) GetLog() *LogChunk {
	if x != nil {
		if x, ok := x.Event.(*JobStatusEvent_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *JobStatusEvent) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*JobStatusEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *JobStatusEvent) GetResult() *TerminalResult {
	if x != nil {
		if x, ok := x.Event.(*JobStatusEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isJobStatusEvent_Event interface {
	isJobStatusEvent_Event()
}

type JobStatusEvent_Phase struct {
	Phase *PhaseChange `protobuf:"bytes,2,opt,name=phase,proto3,oneof"`
}

type JobStatusEvent_Log struct {
	Log *LogChunk `protobuf:"bytes,3,opt,name=log,proto3,oneof"`
}

type JobStatusEvent_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type JobStatusEvent_Result struct {
	Result *TerminalResult `protobuf:"bytes,5,opt,name=result,proto3,oneof"`
}

func (*JobStatusEvent_Phase) isJobStatusEvent_Event() {}

func (*JobStatusEvent_Log) isJobStatusEvent_Event() {}

func (*JobStatusEvent_Heartbeat) isJobStatusEvent_Event() {}

func (*JobStatusEvent_Result) isJobStatusEvent_Event() {}

type PhaseChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseChange) Reset() {
	*x = PhaseChange{}
	mi := &file_guest_v1_guest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseChange) ProtoMessage() {}

func (x *PhaseChange) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseChange.ProtoReflect.Descriptor instead.
func (*PhaseChange) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{8}
}

func (x *PhaseChange) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        LogChunk_Stream        `protobuf:"varint,1,opt,name=stream,proto3,enum=gha.guest.v1.LogChunk_Stream" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_guest_v1_guest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{9}
}

func (x *LogChunk) GetStream() LogChunk_Stream {
	if x != nil {
		return x.Stream
	}
	return LogChunk_STREAM_UNSPECIFIED
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixNanos     int64                  `protobuf:"varint,1,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_guest_v1_guest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{10}
}

func (x *Heartbeat) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

type TerminalResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalResult) Reset() {
	*x = TerminalResult{}
	mi := &file_guest_v1_guest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalResult) ProtoMessage() {}

func (x *TerminalResult) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalResult.ProtoReflect.Descriptor instead.
func (*TerminalResult) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{11}
}

func (x *TerminalResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TerminalResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReattachRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReattachRequest) Reset() {
	*x = ReattachRequest{}
	mi := &file_guest_v1_guest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReattachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReattachRequest) ProtoMessage() {}

func (x *ReattachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReattachRequest.ProtoReflect.Descriptor instead.
func (*ReattachRequest) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{12}
}

type ReattachResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*ExecutionState      `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReattachResponse) Reset() {
	*x = ReattachResponse{}
	mi := &file_guest_v1_guest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReattachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReattachResponse) ProtoMessage() {}

func (x *ReattachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReattachResponse.ProtoReflect.Descriptor instead.
func (*ReattachResponse) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{13}
}

func (x *ReattachResponse) GetExecutions() []*ExecutionState {
	if x != nil {
		return x.Executions
	}
	return nil
}

type ExecutionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Slot          uint32                 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Meta          *JobMeta               `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Phase         string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	Running       bool                   `protobuf:"varint,5,opt,name=running,proto3" json:"running,omitempty"`
	LastSequence  uint64                 `protobuf:"varint,6,opt,name=last_sequence,json=lastSequence,proto3" json:"last_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionState) Reset() {
	*x = ExecutionState{}
	mi := &file_guest_v1_guest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionState) ProtoMessage() {}

func (x *ExecutionState) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionState.ProtoReflect.Descriptor instead.
func (*ExecutionState) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{14}
}

func (x *ExecutionState) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionState) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ExecutionState) GetMeta() *JobMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ExecutionState) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ExecutionState) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ExecutionState) GetLastSequence() uint64 {
	if x != nil {
		return x.LastSequence
	}
	return 0
}

type DrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_guest_v1_guest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{15}
}

type DrainResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Idle             bool                   `protobuf:"varint,1,opt,name=idle,proto3" json:"idle,omitempty"`
	ActiveExecutions uint32                 `protobuf:"varint,2,opt,name=active_executions,json=activeExecutions,proto3" json:"active_executions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DrainResponse) Reset() {
	*x = DrainResponse{}
	mi := &file_guest_v1_guest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainResponse) ProtoMessage() {}

func (x *DrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainResponse.ProtoReflect.Descriptor instead.
func (*DrainResponse) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{16}
}

func (x *DrainResponse) GetIdle() bool {
	if x != nil {
		return x.Idle
	}
	return false
}

func (x *DrainResponse) GetActiveExecutions() uint32 {
	if x != nil {
		return x.ActiveExecutions
	}
	return 0
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_guest_v1_guest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{17}
}

func (x *CancelJobRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_guest_v1_guest_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{18}
}

var File_guest_v1_guest_proto protoreflect.FileDescriptor

const file_guest_v1_guest_proto_rawDesc = "" +
	"\n" +
	"\x14guest/v1/guest.proto\x12\fgha.guest.v1\"\x0e\n" +
	"\fHelloRequest\"\xf1\x01\n" +
	"\rHelloResponse\x12\x17\n" +
	"\aboot_id\x18\x01 \x01(\tR\x06bootId\x12\x1f\n" +
	"\vagent_build\x18\x02 \x01(\tR\n" +
	"agentBuild\x12%\n" +
	"\x0eprotocol_major\x18\x03 \x01(\rR\rprotocolMajor\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12,\n" +
	"\x05slots\x18\x05 \x03(\v2\x16.gha.guest.v1.SlotInfoR\x05slots\x12-\n" +
	"\x12golden_fingerprint\x18\x06 \x01(\tR\x11goldenFingerprint\"W\n" +
	"\bSlotInfo\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04busy\x18\x02 \x01(\bR\x04busy\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\"\x80\x02\n" +
	"\rRunJobRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\rR\x04slot\x12\x1d\n" +
	"\n" +
	"jit_config\x18\x03 \x01(\tR\tjitConfig\x126\n" +
	"\x03env\x18\x04 \x03(\v2$.gha.guest.v1.RunJobRequest.EnvEntryR\x03env\x12)\n" +
	"\x04meta\x18\x05 \x01(\v2\x15.gha.guest.v1.JobMetaR\x04meta\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\aJobMeta\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\x03R\x05jobId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\x03R\x05runId\x12\x1f\n" +
	"\vrunner_name\x18\x04 \x01(\tR\n" +
	"runnerName\"\xbc\x01\n" +
	"\x0eRunJobResponse\x12>\n" +
	"\aoutcome\x18\x01 \x01(\x0e2$.gha.guest.v1.RunJobResponse.OutcomeR\aoutcome\"j\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bACCEPTED\x10\x01\x12\x13\n" +
	"\x0fALREADY_RUNNING\x10\x02\x12\x15\n" +
	"\x11ALREADY_COMPLETED\x10\x03\x12\f\n" +
	"\bCONFLICT\x10\x04\"Z\n" +
	"\x10JobStatusRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12#\n" +
	"\rfrom_sequence\x18\x02 \x01(\x04R\ffromSequence\"\x85\x02\n" +
	"\x0eJobStatusEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x121\n" +
	"\x05phase\x18\x02 \x01(\v2\x19.gha.guest.v1.PhaseChangeH\x00R\x05phase\x12*\n" +
	"\x03log\x18\x03 \x01(\v2\x16.gha.guest.v1.LogChunkH\x00R\x03log\x127\n" +
	"\theartbeat\x18\x04 \x01(\v2\x17.gha.guest.v1.HeartbeatH\x00R\theartbeat\x126\n" +
	"\x06result\x18\x05 \x01(\v2\x1c.gha.guest.v1.TerminalResultH\x00R\x06resultB\a\n" +
	"\x05event\"#\n" +
	"\vPhaseChange\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\"\x8f\x01\n" +
	"\bLogChunk\x125\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x1d.gha.guest.v1.LogChunk.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"8\n" +
	"\x06Stream\x12\x16\n" +
	"\x12STREAM_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x01\x12\n" +
	"\n" +
	"\x06STDERR\x10\x02\"*\n" +
	"\tHeartbeat\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x01 \x01(\x03R\tunixNanos\"G\n" +
	"\x0eTerminalResult\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fReattachRequest\"P\n" +
	"\x10ReattachResponse\x12<\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x1c.gha.guest.v1.ExecutionStateR\n" +
	"executions\"\xc7\x01\n" +
	"\x0eExecutionState\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\rR\x04slot\x12)\n" +
	"\x04meta\x18\x03 \x01(\v2\x15.gha.guest.v1.JobMetaR\x04meta\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x18\n" +
	"\arunning\x18\x05 \x01(\bR\arunning\x12#\n" +
	"\rlast_sequence\x18\x06 \x01(\x04R\flastSequence\"\x0e\n" +
	"\fDrainRequest\"P\n" +
	"\rDrainResponse\x12\x12\n" +
	"\x04idle\x18\x01 \x01(\bR\x04idle\x12+\n" +
	"\x11active_executions\x18\x02 \x01(\rR\x10activeExecutions\"5\n" +
	"\x10CancelJobRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\x13\n" +
	"\x11CancelJobResponse2\xc2\x03\n" +
	"\x11GuestAgentService\x12@\n" +
	"\x05Hello\x12\x1a.gha.guest.v1.HelloRequest\x1a\x1b.gha.guest.v1.HelloResponse\x12C\n" +
	"\x06RunJob\x12\x1b.gha.guest.v1.RunJobRequest\x1a\x1c.gha.guest.v1.RunJobResponse\x12K\n" +
	"\tJobStatus\x12\x1e.gha.guest.v1.JobStatusRequest\x1a\x1c.gha.guest.v1.JobStatusEvent0\x01\x12I\n" +
	"\bReattach\x12\x1d.gha.guest.v1.ReattachRequest\x1a\x1e.gha.guest.v1.ReattachResponse\x12@\n" +
	"\x05Drain\x12\x1a.gha.guest.v1.DrainRequest\x1a\x1b.gha.guest.v1.DrainResponse\x12L\n" +
	"\tCancelJob\x12\x1e.gha.guest.v1.CancelJobRequest\x1a\x1f.gha.guest.v1.CancelJobResponseB;Z9goodkind.io/gha-mac-broker/internal/guestproto;guestprotob\x06proto3"

var (
	file_guest_v1_guest_proto_rawDescOnce sync.Once
	file_guest_v1_guest_proto_rawDescData []byte
)

func file_guest_v1_guest_proto_rawDescGZIP() []byte {
	file_guest_v1_guest_proto_rawDescOnce.Do(func() {
		file_guest_v1_guest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guest_v1_guest_proto_rawDesc), len(file_guest_v1_guest_proto_rawDesc)))
	})
	return file_guest_v1_guest_proto_rawDescData
}

var file_guest_v1_guest_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_guest_v1_guest_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_guest_v1_guest_proto_goTypes = []any{
	(RunJobResponse_Outcome)(0), // 0: gha.guest.v1.RunJobResponse.Outcome
	(LogChunk_Stream)(0),        // 1: gha.guest.v1.LogChunk.Stream
	(*HelloRequest)(nil),        // 2: gha.guest.v1.HelloRequest
	(*HelloResponse)(nil),       // 3: gha.guest.v1.HelloResponse
	(*SlotInfo)(nil),            // 4: gha.guest.v1.SlotInfo
	(*RunJobRequest)(nil),       // 5: gha.guest.v1.RunJobRequest
	(*JobMeta)(nil),             // 6: gha.guest.v1.JobMeta
	(*RunJobResponse)(nil),      // 7: gha.guest.v1.RunJobResponse
	(*JobStatusRequest)(nil),    // 8: gha.guest.v1.JobStatusRequest
	(*JobStatusEvent)(nil),      // 9: gha.guest.v1.JobStatusEvent
	(*PhaseChange)(nil),         // 10: gha.guest.v1.PhaseChange
	(*LogChunk)(nil),            // 11: gha.guest.v1.LogChunk
	(*Heartbeat)(nil),           // 12: gha.guest.v1.Heartbeat
	(*TerminalResult)(nil),      // 13: gha.guest.v1.TerminalResult
	(*ReattachRequest)(nil),     // 14: gha.guest.v1.ReattachRequest
	(*ReattachResponse)(nil),    // 15: gha.guest.v1.ReattachResponse
	(*ExecutionState)(nil),      // 16: gha.guest.v1.ExecutionState
	(*DrainRequest)(nil),        // 17: gha.guest.v1.DrainRequest
	(*DrainResponse)(nil),       // 18: gha.guest.v1.DrainResponse
	(*CancelJobRequest)(nil),    // 19: gha.guest.v1.CancelJobRequest
	(*CancelJobResponse)(nil),   // 20: gha.guest.v1.CancelJobResponse
	nil,                         // 21: gha.guest.v1.RunJobRequest.EnvEntry
}
var file_guest_v1_guest_proto_depIdxs = []int32{
	4,  // 0: gha.guest.v1.HelloResponse.slots:type_name -> gha.guest.v1.SlotInfo
	21, // 1: gha.guest.v1.RunJobRequest.env:type_name -> gha.guest.v1.RunJobRequest.EnvEntry
	6,  // 2: gha.guest.v1.RunJobRequest.meta:type_name -> gha.guest.v1.JobMeta
	0,  // 3: gha.guest.v1.RunJobResponse.outcome:type_name -> gha.guest.v1.RunJobResponse.Outcome
	10, // 4: gha.guest.v1.JobStatusEvent.phase:type_name -> gha.guest.v1.PhaseChange
	11, // 5: gha.guest.v1.JobStatusEvent.log:type_name -> gha.guest.v1.LogChunk
	12, // 6: gha.guest.v1.JobStatusEvent.heartbeat:type_name -> gha.guest.v1.Heartbeat
	13, // 7: gha.guest.v1.JobStatusEvent.result:type_name -> gha.guest.v1.TerminalResult
	1,  // 8: gha.guest.v1.LogChunk.stream:type_name -> gha.guest.v1.LogChunk.Stream
	16, // 9: gha.guest.v1.ReattachResponse.executions:type_name -> gha.guest.v1.ExecutionState
	6,  // 10: gha.guest.v1.ExecutionState.meta:type_name -> gha.guest.v1.JobMeta
	2,  // 11: gha.guest.v1.GuestAgentService.Hello:input_type -> gha.guest.v1.HelloRequest
	5,  // 12: gha.guest.v1.GuestAgentService.RunJob:input_type -> gha.guest.v1.RunJobRequest
	8,  // 13: gha.guest.v1.GuestAgentService.JobStatus:input_type -> gha.guest.v1.JobStatusRequest
	14, // 14: gha.guest.v1.GuestAgentService.Reattach:input_type -> gha.guest.v1.ReattachRequest
	17, // 15: gha.guest.v1.GuestAgentService.Drain:input_type -> gha.guest.v1.DrainRequest
	19, // 16: gha.guest.v1.GuestAgentService.CancelJob:input_type -> gha.guest.v1.CancelJobRequest
	3,  // 17: gha.guest.v1.GuestAgentService.Hello:output_type -> gha.guest.v1.HelloResponse
	7,  // 18: gha.guest.v1.GuestAgentService.RunJob:output_type -> gha.guest.v1.RunJobResponse
	9,  // 19: gha.guest.v1.GuestAgentService.JobStatus:output_type -> gha.guest.v1.JobStatusEvent
	15, // 20: gha.guest.v1.GuestAgentService.Reattach:output_type -> gha.guest.v1.ReattachResponse
	18, // 21: gha.guest.v1.GuestAgentService.Drain:output_type -> gha.guest.v1.DrainResponse
	20, // 22: gha.guest.v1.GuestAgentService.CancelJob:output_type -> gha.guest.v1.CancelJobResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_guest_v1_guest_proto_init() }
func file_guest_v1_guest_proto_init() {
	if File_guest_v1_guest_proto != nil {
		return
	}
	file_guest_v1_guest_proto_msgTypes[7].OneofWrappers = []any{
		(*JobStatusEvent_Phase)(nil),
		(*JobStatusEvent_Log)(nil),
		(*JobStatusEvent_Heartbeat)(nil),
		(*JobStatusEvent_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guest_v1_guest_proto_rawDesc), len(file_guest_v1_guest_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guest_v1_guest_proto_goTypes,
		DependencyIndexes: file_guest_v1_guest_proto_depIdxs,
		EnumInfos:         file_guest_v1_guest_proto_enumTypes,
		MessageInfos:      file_guest_v1_guest_proto_msgTypes,
	}.Build()
	File_guest_v1_guest_proto = out.File
	file_guest_v1_guest_proto_goTypes = nil
	file_guest_v1_guest_proto_depIdxs = nil
}
