// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: guest/v1/guest.proto

package guestprotoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	guestproto "goodkind.io/gha-mac-broker/internal/guestproto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GuestAgentServiceName is the fully-qualified name of the GuestAgentService service.
	GuestAgentServiceName = "gha.guest.v1.GuestAgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GuestAgentServiceHelloProcedure is the fully-qualified name of the GuestAgentService's Hello RPC.
	GuestAgentServiceHelloProcedure = "/gha.guest.v1.GuestAgentService/Hello"
	// GuestAgentServiceRunJobProcedure is the fully-qualified name of the GuestAgentService's RunJob
	// RPC.
	GuestAgentServiceRunJobProcedure = "/gha.guest.v1.GuestAgentService/RunJob"
	// GuestAgentServiceJobStatusProcedure is the fully-qualified name of the GuestAgentService's
	// JobStatus RPC.
	GuestAgentServiceJobStatusProcedure = "/gha.guest.v1.GuestAgentService/JobStatus"
	// GuestAgentServiceReattachProcedure is the fully-qualified name of the GuestAgentService's
	// Reattach RPC.
	GuestAgentServiceReattachProcedure = "/gha.guest.v1.GuestAgentService/Reattach"
	// GuestAgentServiceDrainProcedure is the fully-qualified name of the GuestAgentService's Drain RPC.
	GuestAgentServiceDrainProcedure = "/gha.guest.v1.GuestAgentService/Drain"
	// GuestAgentServiceCancelJobProcedure is the fully-qualified name of the GuestAgentService's
	// CancelJob RPC.
	GuestAgentServiceCancelJobProcedure = "/gha.guest.v1.GuestAgentService/CancelJob"
	// GuestAgentServiceUpdateAgentProcedure is the fully-qualified name of the GuestAgentService's
	// UpdateAgent RPC.
	GuestAgentServiceUpdateAgentProcedure = "/gha.guest.v1.GuestAgentService/UpdateAgent"
)

// GuestAgentServiceClient is a client for the gha.guest.v1.GuestAgentService service.
type GuestAgentServiceClient interface {
	Hello(context.Context, *connect.Request[guestproto.HelloRequest]) (*connect.Response[guestproto.HelloResponse], error)
	RunJob(context.Context, *connect.Request[guestproto.RunJobRequest]) (*connect.Response[guestproto.RunJobResponse], error)
	JobStatus(context.Context, *connect.Request[guestproto.JobStatusRequest]) (*connect.ServerStreamForClient[guestproto.JobStatusEvent], error)
	Reattach(context.Context, *connect.Request[guestproto.ReattachRequest]) (*connect.Response[guestproto.ReattachResponse], error)
	Drain(context.Context, *connect.Request[guestproto.DrainRequest]) (*connect.Response[guestproto.DrainResponse], error)
	CancelJob(context.Context, *connect.Request[guestproto.CancelJobRequest]) (*connect.Response[guestproto.CancelJobResponse], error)
	UpdateAgent(context.Context) *connect.ClientStreamForClient[guestproto.UpdateAgentRequest, guestproto.UpdateAgentResponse]
}

// NewGuestAgentServiceClient constructs a client for the gha.guest.v1.GuestAgentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGuestAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GuestAgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	guestAgentServiceMethods := guestproto.File_guest_v1_guest_proto.Services().ByName("GuestAgentService").Methods()
	return &guestAgentServiceClient{
		hello: connect.NewClient[guestproto.HelloRequest, guestproto.HelloResponse](
			httpClient,
			baseURL+GuestAgentServiceHelloProcedure,
			connect.WithSchema(guestAgentServiceMethods.ByName("Hello")),
			connect.WithClientOptions(opts...),
		),
		runJob: connect.NewClient[guestproto.RunJobRequest, guestproto.RunJobResponse](
			httpClient,
			baseURL+GuestAgentServiceRunJobProcedure,
			connect.WithSchema(guestAgentServiceMethods.ByName("RunJob")),
			connect.WithClientOptions(opts...),
		),
		jobStatus: connect.NewClient[guestproto.JobStatusRequest, guestproto.JobStatusEvent](
			httpClient,
			baseURL+GuestAgentServiceJobStatusProcedure,
			connect.WithSchema(guestAgentServiceMethods.ByName("JobStatus")),
			connect.WithClientOptions(opts...),
		),
		reattach: connect.NewClient[guestproto.ReattachRequest, guestproto.ReattachResponse](
			httpClient,
			baseURL+GuestAgentServiceReattachProcedure,
			connect.WithSchema(guestAgentServiceMethods.ByName("Reattach")),
			connect.WithClientOptions(opts...),
		),
		drain: connect.NewClient[guestproto.DrainRequest, guestproto.DrainResponse](
			httpClient,
			baseURL+GuestAgentServiceDrainProcedure,
			connect.WithSchema(guestAgentServiceMethods.ByName("Drain")),
			connect.WithClientOptions(opts...),
		),
		cancelJob: connect.NewClient[guestproto.CancelJobRequest, guestproto.CancelJobResponse](
			httpClient,
			baseURL+GuestAgentServiceCancelJobProcedure,
			connect.WithSchema(guestAgentServiceMethods.ByName("CancelJob")),
			connect.WithClientOptions(opts...),
		),
		updateAgent: connect.NewClient[guestproto.UpdateAgentRequest, guestproto.UpdateAgentResponse](
			httpClient,
			baseURL+GuestAgentServiceUpdateAgentProcedure,
			connect.WithSchema(guestAgentServiceMethods.ByName("UpdateAgent")),
			connect.WithClientOptions(opts...),
		),
	}
}

// guestAgentServiceClient implements GuestAgentServiceClient.
type guestAgentServiceClient struct {
	hello       *connect.Client[guestproto.HelloRequest, guestproto.HelloResponse]
	runJob      *connect.Client[guestproto.RunJobRequest, guestproto.RunJobResponse]
	jobStatus   *connect.Client[guestproto.JobStatusRequest, guestproto.JobStatusEvent]
	reattach    *connect.Client[guestproto.ReattachRequest, guestproto.ReattachResponse]
	drain       *connect.Client[guestproto.DrainRequest, guestproto.DrainResponse]
	cancelJob   *connect.Client[guestproto.CancelJobRequest, guestproto.CancelJobResponse]
	updateAgent *connect.Client[guestproto.UpdateAgentRequest, guestproto.UpdateAgentResponse]
}

// Hello calls gha.guest.v1.GuestAgentService.Hello.
func (c *guestAgentServiceClient) Hello(ctx context.Context, req *connect.Request[guestproto.HelloRequest]) (*connect.Response[guestproto.HelloResponse], error) {
	return c.hello.CallUnary(ctx, req)
}

// RunJob calls gha.guest.v1.GuestAgentService.RunJob.
func (c *guestAgentServiceClient) RunJob(ctx context.Context, req *connect.Request[guestproto.RunJobRequest]) (*connect.Response[guestproto.RunJobResponse], error) {
	return c.runJob.CallUnary(ctx, req)
}

// JobStatus calls gha.guest.v1.GuestAgentService.JobStatus.
func (c *guestAgentServiceClient) JobStatus(ctx context.Context, req *connect.Request[guestproto.JobStatusRequest]) (*connect.ServerStreamForClient[guestproto.JobStatusEvent], error) {
	return c.jobStatus.CallServerStream(ctx, req)
}

// Reattach calls gha.guest.v1.GuestAgentService.Reattach.
func (c *guestAgentServiceClient) Reattach(ctx context.Context, req *connect.Request[guestproto.ReattachRequest]) (*connect.Response[guestproto.ReattachResponse], error) {
	return c.reattach.CallUnary(ctx, req)
}

// Drain calls gha.guest.v1.GuestAgentService.Drain.
func (c *guestAgentServiceClient) Drain(ctx context.Context, req *connect.Request[guestproto.DrainRequest]) (*connect.Response[guestproto.DrainResponse], error) {
	return c.drain.CallUnary(ctx, req)
}

// CancelJob calls gha.guest.v1.GuestAgentService.CancelJob.
func (c *guestAgentServiceClient) CancelJob(ctx context.Context, req *connect.Request[guestproto.CancelJobRequest]) (*connect.Response[guestproto.CancelJobResponse], error) {
	return c.cancelJob.CallUnary(ctx, req)
}

// UpdateAgent calls gha.guest.v1.GuestAgentService.UpdateAgent.
func (c *guestAgentServiceClient) UpdateAgent(ctx context.Context) *connect.ClientStreamForClient[guestproto.UpdateAgentRequest, guestproto.UpdateAgentResponse] {
	return c.updateAgent.CallClientStream(ctx)
}

// GuestAgentServiceHandler is an implementation of the gha.guest.v1.GuestAgentService service.
type GuestAgentServiceHandler interface {
	Hello(context.Context, *connect.Request[guestproto.HelloRequest]) (*connect.Response[guestproto.HelloResponse], error)
	RunJob(context.Context, *connect.Request[guestproto.RunJobRequest]) (*connect.Response[guestproto.RunJobResponse], error)
	JobStatus(context.Context, *connect.Request[guestproto.JobStatusRequest], *connect.ServerStream[guestproto.JobStatusEvent]) error
	Reattach(context.Context, *connect.Request[guestproto.ReattachRequest]) (*connect.Response[guestproto.ReattachResponse], error)
	Drain(context.Context, *connect.Request[guestproto.DrainRequest]) (*connect.Response[guestproto.DrainResponse], error)
	CancelJob(context.Context, *connect.Request[guestproto.CancelJobRequest]) (*connect.Response[guestproto.CancelJobResponse], error)
	UpdateAgent(context.Context, *connect.ClientStream[guestproto.UpdateAgentRequest]) (*connect.Response[guestproto.UpdateAgentResponse], error)
}

// NewGuestAgentServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGuestAgentServiceHandler(svc GuestAgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	guestAgentServiceMethods := guestproto.File_guest_v1_guest_proto.Services().ByName("GuestAgentService").Methods()
	guestAgentServiceHelloHandler := connect.NewUnaryHandler(
		GuestAgentServiceHelloProcedure,
		svc.Hello,
		connect.WithSchema(guestAgentServiceMethods.ByName("Hello")),
		connect.WithHandlerOptions(opts...),
	)
	guestAgentServiceRunJobHandler := connect.NewUnaryHandler(
		GuestAgentServiceRunJobProcedure,
		svc.RunJob,
		connect.WithSchema(guestAgentServiceMethods.ByName("RunJob")),
		connect.WithHandlerOptions(opts...),
	)
	guestAgentServiceJobStatusHandler := connect.NewServerStreamHandler(
		GuestAgentServiceJobStatusProcedure,
		svc.JobStatus,
		connect.WithSchema(guestAgentServiceMethods.ByName("JobStatus")),
		connect.WithHandlerOptions(opts...),
	)
	guestAgentServiceReattachHandler := connect.NewUnaryHandler(
		GuestAgentServiceReattachProcedure,
		svc.Reattach,
		connect.WithSchema(guestAgentServiceMethods.ByName("Reattach")),
		connect.WithHandlerOptions(opts...),
	)
	guestAgentServiceDrainHandler := connect.NewUnaryHandler(
		GuestAgentServiceDrainProcedure,
		svc.Drain,
		connect.WithSchema(guestAgentServiceMethods.ByName("Drain")),
		connect.WithHandlerOptions(opts...),
	)
	guestAgentServiceCancelJobHandler := connect.NewUnaryHandler(
		GuestAgentServiceCancelJobProcedure,
		svc.CancelJob,
		connect.WithSchema(guestAgentServiceMethods.ByName("CancelJob")),
		connect.WithHandlerOptions(opts...),
	)
	guestAgentServiceUpdateAgentHandler := connect.NewClientStreamHandler(
		GuestAgentServiceUpdateAgentProcedure,
		svc.UpdateAgent,
		connect.WithSchema(guestAgentServiceMethods.ByName("UpdateAgent")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gha.guest.v1.GuestAgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GuestAgentServiceHelloProcedure:
			guestAgentServiceHelloHandler.ServeHTTP(w, r)
		case GuestAgentServiceRunJobProcedure:
			guestAgentServiceRunJobHandler.ServeHTTP(w, r)
		case GuestAgentServiceJobStatusProcedure:
			guestAgentServiceJobStatusHandler.ServeHTTP(w, r)
		case GuestAgentServiceReattachProcedure:
			guestAgentServiceReattachHandler.ServeHTTP(w, r)
		case GuestAgentServiceDrainProcedure:
			guestAgentServiceDrainHandler.ServeHTTP(w, r)
		case GuestAgentServiceCancelJobProcedure:
			guestAgentServiceCancelJobHandler.ServeHTTP(w, r)
		case GuestAgentServiceUpdateAgentProcedure:
			guestAgentServiceUpdateAgentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGuestAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGuestAgentServiceHandler struct{}

func (UnimplementedGuestAgentServiceHandler) Hello(context.Context, *connect.Request[guestproto.HelloRequest]) (*connect.Response[guestproto.HelloResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gha.guest.v1.GuestAgentService.Hello is not implemented"))
}

func (UnimplementedGuestAgentServiceHandler) RunJob(context.Context, *connect.Request[guestproto.RunJobRequest]) (*connect.Response[guestproto.RunJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gha.guest.v1.GuestAgentService.RunJob is not implemented"))
}

func (UnimplementedGuestAgentServiceHandler) JobStatus(context.Context, *connect.Request[guestproto.JobStatusRequest], *connect.ServerStream[guestproto.JobStatusEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("gha.guest.v1.GuestAgentService.JobStatus is not implemented"))
}

func (UnimplementedGuestAgentServiceHandler) Reattach(context.Context, *connect.Request[guestproto.ReattachRequest]) (*connect.Response[guestproto.ReattachResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gha.guest.v1.GuestAgentService.Reattach is not implemented"))
}

func (UnimplementedGuestAgentServiceHandler) Drain(context.Context, *connect.Request[guestproto.DrainRequest]) (*connect.Response[guestproto.DrainResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gha.guest.v1.GuestAgentService.Drain is not implemented"))
}

func (UnimplementedGuestAgentServiceHandler) CancelJob(context.Context, *connect.Request[guestproto.CancelJobRequest]) (*connect.Response[guestproto.CancelJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gha.guest.v1.GuestAgentService.CancelJob is not implemented"))
}

func (UnimplementedGuestAgentServiceHandler) UpdateAgent(context.Context, *connect.ClientStream[guestproto.UpdateAgentRequest]) (*connect.Response[guestproto.UpdateAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gha.guest.v1.GuestAgentService.UpdateAgent is not implemented"))
}
